reporting: "off"
startuppopupversion: 1

git:
  pull:
    mode: rebase
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never

confirmOnQuit: false
quitOnTopLevelReturn: false
