#!/bin/sh

alias p="sudo pacman"
alias dotf="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"
alias vim="nvim"
alias v='vim'
alias dt='dotf'
alias j='cd "$(fd -t d '"'.*'"' $HOME | fzf)"'
alias jh='cd "$(fd -t d '"'.*'"' --hidden $HOME | fzf)"'
alias jg='cd "$(fd -t d '"'.*'"' / | fzf)"'

compdef dotf='git'
compdef dt='git'

vc() { dt ls-tree --full-tree -r HEAD --name-only | sed "s,^,$HOME/," | fzf | xargs -r $EDITOR ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}

