#!/bin/sh

alias \
        c="clear" \
        dexe="docker exec -it" \
        dk="docker" \
        dkc="docker-compose" \
        dt="/usr/bin/git --git-dir=$XDG_CONFIG_HOME/dotfiles.git/ --work-tree=$HOME" \
        dta="dt add -p" \
        dtc="dt commit" \
        dtd="dt diff" \
        dtp="dt push" \
        dts="dt status" \
        gs="git status" \
        j='cd "$(fd -t d -E go '"'.*'"' $HOME | fzf)"' \
        jr='cd "$(fd -t d '"'.*'"' $PWD | fzf)"' \
        jg='cd "$(fd -t d -E $HOME -E /run -E /proc -E /sys -E /dev '"'.*'"' / | fzf)"' \
        jh='cd "$(fd -t d --regex '"'^\.'"' --hidden -E .cargo -E .cache -E go $HOME | fzf)"' \
        jc='cd "$(fd -t d '"'.*'"' $HOME/.config| fzf)"' \
        lg="lazygit" \
        t="tmux" \
        v="vim" \
        vim="nvim"

vc() { dt ls-tree --full-tree -r HEAD --name-only | sed "s,^,$HOME/," | fzf | xargs -r $EDITOR ;}
vf() { fzf | xargs -r $EDITOR ;}
vfr() { fd -t f ".*" /etc | fzf | xargs -r sudoedit ;}

