#!/bin/sh

alias \
        p="sudo pacman" \
        gs="git status" \
        dt="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME" \
        dts='dt status' \
        dta='dt add -p' \
        dtc='dt commit' \
        dtd='dt diff' \
        dtp='dt push' \
        dk="docker" \
        dkc="docker-compose" \
        dexe="docker exec -it" \
        vim="nvim" \
        v='vim' \
        j='cd "$(fd -t d '"'.*'"' $HOME | fzf)"' \
        jh='cd "$(fd -t d '"'.*'"' --hidden $HOME | fzf)"' \
        jg='cd "$(fd -t d '"'.*'"' / | fzf)"'

vc() { dt ls-tree --full-tree -r HEAD --name-only | sed "s,^,$HOME/," | fzf | xargs -r $EDITOR ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}

